import jwt_decode from 'jwt-decode'
import { accessToken } from '@common/types'

const fakeAccessToken =
  'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImxwdnRKM2dMejM2Yzd5S2prQTZILVQzNmVwUHg4OVAyNXY4cG9SQUNpbyJ9.eyJleHAiOjE2NDAyNzEyNTQsImlhdCI6MTY0MDI3MDY1NCwianRpIjoiMDZiNjgzYzItNDcwOS00OTdmLWJjODEtZWUwZGRmYmQyNGQ1IiwiaXNzIjoiaHR0cDovL3Rlc3QtaXNzdWVyIiwiYXVkIjpbImFkbWluLXBhbmVsIiwiYWNjb3VudCJdLCJzdWIiOiI0YWU0NTQzOS02N2U5LTQ2YzUtYjhhOC1iZGNlZWE0ZDE4ZGIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJjaGVzcyIsInNlc3Npb25fc3RhdGUiOiI0NzI5NjMzMC03MzBmLTQxYzItYmI5Mi1mN2Y1YWJiYzE4NDgiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFkbWluLXBhbmVsIjp7InJvbGVzIjpbImFkbWluIl19LCJjaGVzcyI6eyJyb2xlcyI6WyJQbGF5ZXIiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJzaWQiOiJhMWJhMjcxNS0wMGYwLTQyMDEtYThiYS1hMjQ0OGExMTJhYWUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IlRlc3QgVXNlciIsInByZWZlcnJlZF91c2VybmFtZSI6InRlc3QiLCJnaXZlbl9uYW1lIjoiVGVzdCIsImZhbWlseV9uYW1lIjoiVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSJ9.I3yv2ndPt55P8NOYd1iLIzfw0JSZc8UrgaZttbICjfl0_lC3OYRvUhhbOFTVuDfUnucNombzXH8-2WGkG2LXMR95ENG6j_NbfnCaMpxEn4xNvWRaSclSh8VL83ff0R4azX8zlvNhd1d5IGP9rbb3wvygw892WgaW_qh-cgPlydM'

export default fakeAccessToken

export const decodedFakeAccessToken = jwt_decode(fakeAccessToken) as accessToken
